### ISSUE TITLE
Can't publish package due to duplicate name

### ISSUE THREAD

**Issue by Zylvian** [d1618033/gh-action-python-publish-using-poetry#1]
Hi!

My package won't get published as it contains a duplciate name to a package online. Is it possible to send in args for -r (repository)?

**Comment by d1618033** [comment]
Hey!

Sorry for the delay. I added two additional arguments. `twine_upload_args` and `poetry_build_args` 
In your case you should use the `twine_upload_args` as such:
```
        - name: Build and publish
          uses: d1618033/gh-action-python-publish-using-poetry@master
          with:
            pypi_username: ${{ secrets.PYPI_USERNAME }}
            pypi_password: ${{ secrets.PYPI_PASSWORD }}
            twine_upload_args: '-r myrepo'
```
